from typing import Optional, List, Dict, Any, Callable, Generator, Set, Tuple
"""
GP PRO AGENT — AI Code Generator
Generate complete working programs from natural language description.
Supports: Python, Ladder Logic, PLC Structured Text, Shell scripts.
"""
import re, time
from pathlib import Path

TEMPLATES = {
    "modbus_client": '''#!/usr/bin/env python3
"""
{description}
Generated by GP PRO AGENT Code Generator
"""
from pymodbus.client import ModbusTcpClient
import time, logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

PLC_IP   = "{ip}"
PLC_PORT = 502
UNIT_ID  = 1

def connect():
    client = ModbusTcpClient(PLC_IP, port=PLC_PORT)
    if client.connect():
        logger.info(f"Connected to PLC at {{PLC_IP}}")
        return client
    raise ConnectionError(f"Cannot connect to {{PLC_IP}}")

def read_registers(client, address, count=10):
    result = client.read_holding_registers(address, count, unit=UNIT_ID)
    if result.isError():
        logger.error(f"Read error: {{result}}")
        return None
    return result.registers

def write_register(client, address, value):
    result = client.write_register(address, value, unit=UNIT_ID)
    if result.isError():
        logger.error(f"Write error: {{result}}")
        return False
    logger.info(f"Written {{value}} to address {{address}}")
    return True

def monitor_loop(client, addresses, interval=1.0):
    logger.info("Starting monitor loop. Press Ctrl+C to stop.")
    try:
        while True:
            for addr in addresses:
                regs = read_registers(client, addr, 1)
                if regs:
                    logger.info(f"Address {{addr}}: {{regs[0]}}")
            time.sleep(interval)
    except KeyboardInterrupt:
        logger.info("Monitor stopped.")

if __name__ == "__main__":
    client = connect()
    try:
        monitor_loop(client, [{addresses}])
    finally:
        client.close()
''',
    "gui_automation": '''#!/usr/bin/env python3
"""
{description}
Generated by GP PRO AGENT Code Generator
"""
import pyautogui, time, subprocess, sys
pyautogui.FAILSAFE = True
pyautogui.PAUSE    = 0.3

def wait_for_window(title, timeout=10):
    import time
    start = time.time()
    while time.time() - start < timeout:
        windows = pyautogui.getAllWindows() if hasattr(pyautogui,'getAllWindows') else []
        for w in windows:
            if title.lower() in w.title.lower():
                w.activate()
                return True
        time.sleep(0.5)
    return False

def open_application(app_name):
    print(f"Opening {{app_name}}...")
    subprocess.Popen(app_name, shell=True)
    time.sleep(2)

def type_text(text, field_x=None, field_y=None):
    if field_x and field_y:
        pyautogui.click(field_x, field_y)
        time.sleep(0.3)
    pyautogui.typewrite(text, interval=0.05)

def click_button(x, y, description=""):
    print(f"Clicking {{description or f'position ({{x}},{{y}})'}}...")
    pyautogui.moveTo(x, y, duration=0.3)
    pyautogui.click()
    time.sleep(0.5)

def take_screenshot(filename="screenshot.png"):
    img = pyautogui.screenshot()
    img.save(filename)
    print(f"Screenshot saved: {{filename}}")
    return img

def main():
    print("{description}")
    print("Starting automation...")
    # TODO: Add your automation steps here
    # Example:
    # open_application("notepad.exe")
    # time.sleep(1)
    # type_text("Hello from GP PRO AGENT!")
    # take_screenshot("result.png")
    print("Automation complete!")

if __name__ == "__main__":
    main()
''',
    "plc_structured_text": '''(* 
   {description}
   Generated by GP PRO AGENT Code Generator
   IEC 61131-3 Structured Text
*)

PROGRAM {program_name}
VAR
    (* Inputs *)
    xStart      : BOOL;   (* Start command *)
    xStop       : BOOL;   (* Stop command *)
    xFault      : BOOL;   (* Fault input *)
    
    (* Outputs *)
    xMotorRun   : BOOL;   (* Motor run output *)
    xAlarmLight : BOOL;   (* Alarm indicator *)
    
    (* Internal *)
    xRunReq     : BOOL;   (* Run request latch *)
    tonDelay    : TON;    (* Start delay timer *)
    iCounter    : INT;    (* Operation counter *)
END_VAR

(* Safety check first *)
IF xFault THEN
    xMotorRun   := FALSE;
    xAlarmLight := TRUE;
    xRunReq     := FALSE;
    RETURN;
END_IF

(* Run latch logic *)
IF xStart AND NOT xStop THEN
    xRunReq := TRUE;
END_IF

IF xStop THEN
    xRunReq := FALSE;
END_IF

(* Start delay - 2 second delay before motor starts *)
tonDelay(IN := xRunReq, PT := T#2S);

(* Motor output *)
xMotorRun := tonDelay.Q AND xRunReq;

(* Count operations *)
IF xMotorRun THEN
    iCounter := iCounter + 1;
END_IF

(* Reset alarm when fault cleared *)
xAlarmLight := xFault;

END_PROGRAM
''',
    "data_logger": '''#!/usr/bin/env python3
"""
{description}
Generated by GP PRO AGENT Code Generator
"""
import csv, time, os, datetime
from pathlib import Path

LOG_DIR      = Path("C:/GPProAgent/logs/data")
LOG_INTERVAL = {interval}  # seconds
MAX_ROWS     = 10000

LOG_DIR.mkdir(parents=True, exist_ok=True)

def get_log_file():
    date = datetime.datetime.now().strftime("%Y-%m-%d")
    return LOG_DIR / f"datalog_{{date}}.csv"

def log_data(values: dict):
    log_file  = get_log_file()
    file_exists = log_file.exists()
    with open(log_file, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["timestamp"]+list(values.keys()))
        if not file_exists:
            writer.writeheader()
        row = {{"timestamp": datetime.datetime.now().isoformat()}}
        row.update(values)
        writer.writerow(row)

def read_sensor_data():
    """Replace this with actual sensor reading code."""
    import random
    return {{
        "temperature": round(random.uniform(20, 80), 2),
        "pressure":    round(random.uniform(0, 10), 3),
        "flow_rate":   round(random.uniform(0, 100), 1),
        "status":      "OK"
    }}

def main():
    print(f"Data Logger started. Logging every {{LOG_INTERVAL}}s to {{LOG_DIR}}")
    print("Press Ctrl+C to stop.")
    try:
        while True:
            data = read_sensor_data()
            log_data(data)
            print(f"[{{datetime.datetime.now().strftime('%H:%M:%S')}}] "
                  f"T={{data.get('temperature')}} P={{data.get('pressure')}}")
            time.sleep(LOG_INTERVAL)
    except KeyboardInterrupt:
        print("\\nLogger stopped.")

if __name__ == "__main__":
    main()
''',
}

class CodeGenerator:
    def __init__(self, output_path):
        self.output_path = Path(output_path) / "generated_code"
        self.output_path.mkdir(parents=True, exist_ok=True)
        self._count = 0

    def generate(self, description: str, llm_callback=None) -> dict:
        """Generate code from natural language description."""
        q = description.lower()
        self._count += 1
        timestamp = int(time.time())

        # Detect what type of code to generate
        if any(w in q for w in ["modbus","plc connect","read register","write register","plc communication"]):
            code, lang, ext = self._gen_modbus(description)
        elif any(w in q for w in ["gui automat","click button","automate software","pyautogui","screen automat"]):
            code, lang, ext = self._gen_gui(description)
        elif any(w in q for w in ["structured text","iec 61131","plc program","function block","st program"]):
            code, lang, ext = self._gen_plc_st(description)
        elif any(w in q for w in ["data log","log sensor","record data","csv log","monitor and log"]):
            code, lang, ext = self._gen_datalogger(description)
        elif llm_callback:
            # Use LLM for general code
            prompt = (f"Write a complete working Python script for:\n{description}\n\n"
                     "Include imports, main function, error handling, and comments.")
            code = llm_callback(prompt)
            lang = "python"
            ext  = ".py"
        else:
            code = self._gen_generic(description)
            lang = "python"
            ext  = ".py"

        # Save to file
        filename = f"gp_agent_{timestamp}{ext}"
        filepath = self.output_path / filename
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(code)

        return {
            "code":        code,
            "language":    lang,
            "filename":    filename,
            "filepath":    str(filepath),
            "lines":       len(code.split("\n")),
            "description": description,
        }

    def _gen_modbus(self, desc):
        ip = "192.168.1.1"
        m  = re.search(r'(\d+\.\d+\.\d+\.\d+)', desc)
        if m: ip = m.group(1)
        addrs = "0, 1, 2, 3"
        code = TEMPLATES["modbus_client"].format(
            description=desc, ip=ip, addresses=addrs)
        return code, "python", ".py"

    def _gen_gui(self, desc):
        code = TEMPLATES["gui_automation"].format(description=desc)
        return code, "python", ".py"

    def _gen_plc_st(self, desc):
        name = "MainProgram"
        m = re.search(r'for (\w+)', desc, re.I)
        if m: name = m.group(1).replace(" ","_")
        code = TEMPLATES["plc_structured_text"].format(
            description=desc, program_name=name)
        return code, "structured_text", ".st"

    def _gen_datalogger(self, desc):
        interval = 5
        m = re.search(r'every (\d+)', desc)
        if m: interval = int(m.group(1))
        code = TEMPLATES["data_logger"].format(
            description=desc, interval=interval)
        return code, "python", ".py"

    def _gen_generic(self, desc):
        return (f'#!/usr/bin/env python3\n'
                f'"""\n{desc}\nGenerated by GP PRO AGENT\n"""\n\n'
                f'import os, sys, time\n\n'
                f'def main():\n'
                f'    print("GP PRO AGENT Generated Script")\n'
                f'    print("Task: {desc}")\n'
                f'    # TODO: Add implementation here\n'
                f'    pass\n\n'
                f'if __name__ == "__main__":\n'
                f'    main()\n')

    @property
    def generated_count(self):
        return self._count
