"""
GP PRO AGENT - Natural Language to PLC Programming
Describe ladder logic in plain English.
AI converts to IEC 61131-3 Structured Text and Ladder Logic.
"""
import re, json
from pathlib import Path
from datetime import datetime

class PLCProgram:
    def __init__(self, name: str, description: str):
        self.name        = name
        self.description = description
        self.variables   = []
        self.rungs       = []
        self.st_code     = ""
        self.created     = datetime.now().isoformat()

    def to_dict(self):
        return {
            "name":        self.name,
            "description": self.description,
            "variables":   self.variables,
            "rungs":       self.rungs,
            "st_code":     self.st_code,
            "created":     self.created,
        }

    def to_structured_text(self) -> str:
        lines = [
            f"(* Program: {self.name} *)",
            f"(* Description: {self.description} *)",
            f"(* Generated by GP PRO AGENT - NL PLC Compiler *)",
            "",
            f"PROGRAM {self.name.replace(' ','_')}",
            "VAR",
        ]
        for var in self.variables:
            lines.append(f"    {var['name']:<20}: {var['type']};  (* {var['desc']} *)")
        lines += ["END_VAR", "", self.st_code, "", "END_PROGRAM"]
        return "\n".join(lines)

    def to_ladder_description(self) -> str:
        result = f"LADDER LOGIC: {self.name}\n"
        result += "=" * 50 + "\n"
        for i, rung in enumerate(self.rungs):
            result += f"\nRung {i+1:03d}: {rung['description']}\n"
            result += f"  Logic: {rung['logic']}\n"
            if rung.get("comment"):
                result += f"  Note: {rung['comment']}\n"
        return result


class NLPLCCompiler:
    """
    Converts natural language descriptions to PLC programs.

    Examples:
    'When start button pressed and motor not running, energize motor coil'
    -> XIC(Start_PB) XIO(Motor_Run) OTE(Motor_Coil)

    'After 5 seconds of motor running, turn on conveyor'
    -> TON(Motor_Timer, 5000ms) OTE(Conveyor_On)
    """
    def __init__(self, brain_root: str, llm_callback=None):
        self._path      = Path(brain_root) / "nl_plc"
        self._path.mkdir(parents=True, exist_ok=True)
        self._llm       = llm_callback
        self._programs  = {}
        self._load()

        # Pattern library for NL -> PLC translation
        self._patterns  = {
            "when_pressed":   self._parse_when_pressed,
            "after_time":     self._parse_after_time,
            "if_condition":   self._parse_if_condition,
            "count_until":    self._parse_count_until,
            "motor_control":  self._parse_motor_control,
            "safety_circuit": self._parse_safety,
            "pid_control":    self._parse_pid,
            "sequence":       self._parse_sequence,
        }

    def compile(self, description: str,
                program_name: str = None) -> PLCProgram:
        """Convert English description to PLC program."""
        name    = program_name or f"Program_{int(__import__('time').time())}"
        program = PLCProgram(name, description)
        desc_l  = description.lower()

        # Detect program type and apply patterns
        if any(w in desc_l for w in ["motor","start","stop","run"]):
            self._parse_motor_control(program, description)
        elif any(w in desc_l for w in ["count","counter","batch"]):
            self._parse_count_until(program, description)
        elif any(w in desc_l for w in ["timer","after","delay","seconds"]):
            self._parse_after_time(program, description)
        elif any(w in desc_l for w in ["sequence","step","stage","phase"]):
            self._parse_sequence(program, description)
        elif any(w in desc_l for w in ["safety","estop","emergency"]):
            self._parse_safety(program, description)
        elif any(w in desc_l for w in ["pid","temperature","pressure","control"]):
            self._parse_pid(program, description)
        else:
            self._parse_general(program, description)

        # Use LLM for enhanced generation if available
        if self._llm:
            enhanced = self._llm_enhance(program, description)
            if enhanced:
                program.st_code = enhanced

        self._programs[name] = program
        self._save()
        return program

    def _parse_motor_control(self, prog: PLCProgram,
                             desc: str):
        """Parse motor start/stop descriptions."""
        prog.variables = [
            {"name":"xStartPB",    "type":"BOOL","desc":"Start pushbutton NC"},
            {"name":"xStopPB",     "type":"BOOL","desc":"Stop pushbutton NC"},
            {"name":"xEStop",      "type":"BOOL","desc":"E-Stop NC hardwired"},
            {"name":"xMotorRun",   "type":"BOOL","desc":"Motor run output"},
            {"name":"xMotorFault", "type":"BOOL","desc":"Motor fault input"},
            {"name":"xRunLamp",    "type":"BOOL","desc":"Run indicator lamp"},
            {"name":"xFaultLamp",  "type":"BOOL","desc":"Fault indicator lamp"},
            {"name":"tonStartDly", "type":"TON", "desc":"Start delay timer"},
        ]
        prog.rungs = [
            {
                "description": "Start latch with stop and fault interlock",
                "logic": "XIC(xStartPB) XIO(xStopPB) XIO(xMotorFault) XIO(xEStop) OTL(xMotorRun)",
                "comment": "Motor starts only if no fault, stop not pressed, e-stop OK",
            },
            {
                "description": "Stop unlatch",
                "logic": "XIC(xStopPB) OTU(xMotorRun)",
                "comment": "Stop button unlatches motor",
            },
            {
                "description": "E-Stop and fault unlatch",
                "logic": "XIC(xMotorFault) OTU(xMotorRun)",
                "comment": "Fault clears motor latch",
            },
            {
                "description": "Run lamp output",
                "logic": "XIC(xMotorRun) OTE(xRunLamp)",
                "comment": "Lamp on when motor running",
            },
            {
                "description": "Fault lamp output",
                "logic": "XIC(xMotorFault) OTE(xFaultLamp)",
                "comment": "Fault lamp indicator",
            },
        ]
        prog.st_code = """(* Motor Start/Stop Control *)
(* Start latch logic *)
IF xStartPB AND NOT xStopPB AND NOT xMotorFault AND NOT xEStop THEN
    xMotorRun := TRUE;
END_IF

(* Stop conditions *)
IF xStopPB OR xMotorFault OR NOT xEStop THEN
    xMotorRun := FALSE;
END_IF

(* Indicator lamps *)
xRunLamp   := xMotorRun;
xFaultLamp := xMotorFault;"""

    def _parse_after_time(self, prog: PLCProgram, desc: str):
        """Parse timer-based descriptions."""
        import re
        seconds = 5
        m = re.search(r'(\d+)\s*(?:second|sec|s)', desc, re.I)
        if m:
            seconds = int(m.group(1))
        ms = seconds * 1000

        prog.variables = [
            {"name":"xInput",   "type":"BOOL","desc":"Input trigger"},
            {"name":"xOutput",  "type":"BOOL","desc":"Timed output"},
            {"name":"tonDelay", "type":"TON", "desc":f"{seconds}s on-delay timer"},
        ]
        prog.rungs = [
            {
                "description": f"Timer rung - {seconds} second delay",
                "logic": f"XIC(xInput) TON(tonDelay, {ms})",
                "comment": f"Timer starts when xInput is TRUE",
            },
            {
                "description": "Output when timer done",
                "logic": "XIC(tonDelay.DN) OTE(xOutput)",
                "comment": "Output energized after timer preset reached",
            },
        ]
        prog.st_code = f"""(* Timer Control - {seconds} second delay *)
tonDelay(IN := xInput, PT := T#{seconds}S);

IF tonDelay.Q THEN
    xOutput := TRUE;
ELSE
    xOutput := FALSE;
END_IF"""

    def _parse_count_until(self, prog: PLCProgram, desc: str):
        """Parse counter descriptions."""
        import re
        count = 100
        m = re.search(r'(\d+)\s*(?:times|parts|units|count)', desc, re.I)
        if m:
            count = int(m.group(1))

        prog.variables = [
            {"name":"xCountPulse", "type":"BOOL","desc":"Count input pulse"},
            {"name":"xReset",      "type":"BOOL","desc":"Counter reset"},
            {"name":"xBatchDone",  "type":"BOOL","desc":"Batch complete output"},
            {"name":"ctuBatch",    "type":"CTU", "desc":f"Count to {count}"},
            {"name":"iCount",      "type":"INT", "desc":"Current count value"},
        ]
        prog.st_code = f"""(* Counter Control - Count to {count} *)
ctuBatch(CU := xCountPulse, R := xReset, PV := {count});

iCount    := ctuBatch.CV;
xBatchDone := ctuBatch.Q;

(* Auto reset after batch done *)
IF ctuBatch.Q THEN
    (* Batch complete - add your action here *)
    xReset := TRUE;
ELSE
    xReset := FALSE;
END_IF"""

    def _parse_safety(self, prog: PLCProgram, desc: str):
        """Parse safety circuit descriptions."""
        prog.variables = [
            {"name":"xEStop1",     "type":"BOOL","desc":"E-Stop 1 NC"},
            {"name":"xEStop2",     "type":"BOOL","desc":"E-Stop 2 NC"},
            {"name":"xSafetyGate", "type":"BOOL","desc":"Safety gate NC"},
            {"name":"xLightCurt",  "type":"BOOL","desc":"Light curtain NC"},
            {"name":"xSafetyOK",   "type":"BOOL","desc":"Safety circuit OK"},
            {"name":"xReset",      "type":"BOOL","desc":"Manual reset button"},
            {"name":"xMachineRun", "type":"BOOL","desc":"Machine run enable"},
        ]
        prog.st_code = """(* Safety Circuit - SIL 2 *)
(* All safety devices are NC - TRUE = safe, FALSE = fault *)
xSafetyOK := xEStop1 AND xEStop2
             AND xSafetyGate AND xLightCurt;

(* Machine can only run when safety OK and reset pressed *)
IF xSafetyOK AND xReset THEN
    xMachineRun := TRUE;
END_IF

(* Immediate stop on any safety fault *)
IF NOT xSafetyOK THEN
    xMachineRun := FALSE;
END_IF"""

    def _parse_pid(self, prog: PLCProgram, desc: str):
        """Parse PID control descriptions."""
        prog.variables = [
            {"name":"rSetpoint",  "type":"REAL","desc":"Temperature setpoint"},
            {"name":"rProcessVar","type":"REAL","desc":"Current temperature"},
            {"name":"rOutput",    "type":"REAL","desc":"PID output 0-100%"},
            {"name":"rKp",        "type":"REAL","desc":"Proportional gain"},
            {"name":"rKi",        "type":"REAL","desc":"Integral gain"},
            {"name":"rKd",        "type":"REAL","desc":"Derivative gain"},
            {"name":"rError",     "type":"REAL","desc":"Current error"},
            {"name":"rIntegral",  "type":"REAL","desc":"Integral accumulator"},
        ]
        prog.st_code = """(* PID Temperature Control *)
rKp := 2.0;   (* Proportional gain *)
rKi := 0.1;   (* Integral gain *)
rKd := 0.05;  (* Derivative gain *)

rError    := rSetpoint - rProcessVar;
rIntegral := rIntegral + (rError * rKi);

(* Clamp integral *)
IF rIntegral > 100.0 THEN rIntegral := 100.0; END_IF
IF rIntegral < 0.0   THEN rIntegral := 0.0;   END_IF

rOutput := (rKp * rError) + rIntegral;

(* Clamp output 0-100% *)
IF rOutput > 100.0 THEN rOutput := 100.0; END_IF
IF rOutput < 0.0   THEN rOutput := 0.0;   END_IF"""

    def _parse_sequence(self, prog: PLCProgram, desc: str):
        """Parse sequential operation descriptions."""
        prog.variables = [
            {"name":"iStep",      "type":"INT", "desc":"Current step"},
            {"name":"xStartSeq",  "type":"BOOL","desc":"Start sequence"},
            {"name":"xStepDone",  "type":"BOOL","desc":"Step complete feedback"},
            {"name":"xSeqActive", "type":"BOOL","desc":"Sequence running"},
            {"name":"tonStep",    "type":"TON", "desc":"Step timer"},
        ]
        prog.st_code = """(* Sequential Control - State Machine *)
CASE iStep OF
    0: (* IDLE *)
        IF xStartSeq THEN
            iStep := 1;
            xSeqActive := TRUE;
        END_IF

    1: (* STEP 1 - Initialize *)
        (* Add Step 1 actions here *)
        tonStep(IN := TRUE, PT := T#2S);
        IF tonStep.Q THEN
            tonStep(IN := FALSE);
            iStep := 2;
        END_IF

    2: (* STEP 2 - Process *)
        (* Add Step 2 actions here *)
        IF xStepDone THEN
            iStep := 3;
        END_IF

    3: (* STEP 3 - Complete *)
        (* Add completion actions *)
        iStep      := 0;
        xSeqActive := FALSE;

    ELSE
        iStep := 0;  (* Unknown step - reset *)
END_CASE"""

    def _parse_general(self, prog: PLCProgram, desc: str):
        """Parse general descriptions."""
        # Extract inputs and outputs from description
        inputs  = re.findall(r'\b(\w+(?:\s+\w+)?)\s+(?:input|button|sensor|switch)', desc, re.I)
        outputs = re.findall(r'\b(\w+(?:\s+\w+)?)\s+(?:output|motor|valve|lamp)', desc, re.I)

        prog.variables = []
        for i, inp in enumerate(inputs[:5]):
            name = inp.replace(" ","_").upper()
            prog.variables.append({"name":f"x{name}","type":"BOOL","desc":inp})
        for i, out in enumerate(outputs[:5]):
            name = out.replace(" ","_").upper()
            prog.variables.append({"name":f"y{name}","type":"BOOL","desc":out})

        prog.st_code = f"""(* Custom Program: {desc[:50]} *)
(* Add your logic here *)
(* Inputs:  {', '.join(inputs[:3]) if inputs else 'None detected'} *)
(* Outputs: {', '.join(outputs[:3]) if outputs else 'None detected'} *)
"""

    def _llm_enhance(self, prog: PLCProgram,
                     desc: str) -> Optional[str]:
        """Use LLM to enhance the generated code."""
        try:
            prompt = (
                f"You are a PLC programming expert.\n"
                f"Convert this description to IEC 61131-3 Structured Text:\n"
                f"'{desc}'\n\n"
                f"Existing variables:\n"
                + "\n".join(f"{v['name']}: {v['type']}"
                           for v in prog.variables) +
                "\n\nWrite only the ST code body, no PROGRAM/END_PROGRAM wrapper."
            )
            return self._llm("coder", prompt)
        except Exception:
            return None

    def save_program(self, prog: PLCProgram,
                     output_dir: str = None) -> str:
        """Save program to file."""
        save_dir = Path(output_dir) if output_dir else self._path
        save_dir.mkdir(parents=True, exist_ok=True)

        st_file  = save_dir / f"{prog.name}.st"
        st_file.write_text(prog.to_structured_text(),
                           encoding="utf-8")

        info_file = save_dir / f"{prog.name}.json"
        with open(info_file,"w") as f:
            json.dump(prog.to_dict(), f, indent=2)

        return str(st_file)

    def list_programs(self) -> list:
        return [{"name": k, "desc": v.description[:50]}
                for k,v in self._programs.items()]

    def _save(self):
        try:
            data = {k: v.to_dict()
                    for k,v in self._programs.items()}
            with open(self._path/"programs.json","w") as f:
                json.dump(data, f, indent=2)
        except Exception as e:
            print(f"[NL-PLC] Save error: {e}")

    def _load(self):
        try:
            path = self._path / "programs.json"
            if path.exists():
                with open(path) as f:
                    data = json.load(f)
                for name, d in data.items():
                    p = PLCProgram(d["name"], d["description"])
                    p.variables = d.get("variables", [])
                    p.rungs     = d.get("rungs", [])
                    p.st_code   = d.get("st_code", "")
                    self._programs[name] = p
                print(f"[NL-PLC] Loaded {len(self._programs)} programs")
        except Exception:
            self._programs = {}
