"""
GP PRO AGENT - Professional PDF Report Generator
Generates complete professional reports automatically.
Supports: Maintenance reports, PLC documentation,
          Alarm analysis, Trend reports.
"""
import json, time, os
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any, Optional

class ReportSection:
    def __init__(self, title: str, content: str,
                 section_type: str = "text"):
        self.title   = title
        self.content = content
        self.type    = section_type  # text, table, chart, code
        self.data    = None

class Report:
    def __init__(self, title: str, report_type: str,
                 author: str = "GP PRO AGENT"):
        self.title      = title
        self.type       = report_type
        self.author     = author
        self.created    = datetime.now()
        self.sections   = []
        self.metadata   = {}

    def add_section(self, section: ReportSection):
        self.sections.append(section)

    def add_text(self, title: str, content: str):
        self.add_section(ReportSection(title, content, "text"))

    def add_table(self, title: str, headers: List[str],
                  rows: List[List]):
        section      = ReportSection(title, "", "table")
        section.data = {"headers": headers, "rows": rows}
        self.add_section(section)


class ReportGenerator:
    """
    Generates professional reports in multiple formats.
    HTML (always), PDF (if reportlab installed).
    """
    def __init__(self, brain_root: str,
                 notify_callback=None):
        self._path    = Path(brain_root) / "reports"
        self._path.mkdir(parents=True, exist_ok=True)
        self._notify  = notify_callback or print
        self._reports = []

    def generate_maintenance_report(
            self, equipment_data: List[dict],
            maintenance_schedule: List[dict]) -> Report:
        """Generate maintenance status report."""
        report = Report(
            "Equipment Maintenance Report",
            "maintenance")
        report.add_text(
            "Executive Summary",
            f"Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
            f"Total equipment monitored: {len(equipment_data)}\n"
            f"Equipment requiring immediate attention: "
            f"{sum(1 for e in equipment_data if e.get('health_score',100) < 50)}")

        # Equipment health table
        report.add_table(
            "Equipment Health Status",
            ["Equipment", "Health %", "Failure Prob %", "Est. Failure (days)", "Anomalies"],
            [[e.get("name","?"),
              f"{e.get('health_score',100):.1f}%",
              f"{e.get('failure_prob',0):.1f}%",
              str(e.get("est_failure", "N/A")),
              str(e.get("anomalies", 0))]
             for e in equipment_data])

        # Maintenance schedule
        if maintenance_schedule:
            report.add_table(
                "Recommended Maintenance Schedule",
                ["Equipment", "Health %", "Urgency", "Days Until Failure"],
                [[s.get("equipment","?"),
                  f"{s.get('health',100):.0f}%",
                  s.get("urgency","PLANNED"),
                  str(s.get("days_until","N/A"))]
                 for s in maintenance_schedule])

        report.add_text(
            "Recommendations",
            self._generate_recommendations(equipment_data))
        return report

    def generate_plc_documentation(
            self, program_code: str,
            variables: List[dict],
            program_name: str) -> Report:
        """Generate PLC program documentation."""
        report = Report(
            f"PLC Program Documentation: {program_name}",
            "plc_documentation")

        report.add_text("Program Overview",
            f"Program: {program_name}\n"
            f"Generated: {datetime.now().strftime('%Y-%m-%d')}\n"
            f"Generated by: GP PRO AGENT NL-PLC Compiler\n"
            f"Standard: IEC 61131-3 Structured Text")

        if variables:
            report.add_table(
                "Variable Declaration",
                ["Name", "Type", "Description"],
                [[v.get("name","?"),
                  v.get("type","BOOL"),
                  v.get("desc","")]
                 for v in variables])

        section      = ReportSection(
            "Program Code", program_code, "code")
        report.add_section(section)

        report.add_text(
            "Safety Notes",
            "IMPORTANT: Always test in simulation before deployment.\n"
            "Verify all safety interlocks before going online.\n"
            "Follow LOTO procedures during maintenance.\n"
            "Ensure SIL rating matches risk assessment.")
        return report

    def generate_alarm_report(
            self, alarms: List[dict],
            period: str = "Last 24 Hours") -> Report:
        """Generate alarm analysis report."""
        report = Report(
            f"Alarm Analysis Report - {period}",
            "alarm_analysis")

        critical = [a for a in alarms
                   if a.get("severity") == "CRITICAL"]
        warnings = [a for a in alarms
                   if a.get("severity") == "WARNING"]

        report.add_text(
            "Summary",
            f"Period: {period}\n"
            f"Total alarms: {len(alarms)}\n"
            f"Critical: {len(critical)}\n"
            f"Warnings: {len(warnings)}")

        if alarms:
            report.add_table(
                "Alarm Log",
                ["Time", "Severity", "Description"],
                [[a.get("time","?")[:19],
                  a.get("severity","INFO"),
                  a.get("text","?")[:60]]
                 for a in alarms[:50]])

        return report

    def _generate_recommendations(
            self, equipment_data: List[dict]) -> str:
        recs = []
        for eq in equipment_data:
            health = eq.get("health_score", 100)
            name   = eq.get("name", "Equipment")
            if health < 30:
                recs.append(
                    f"CRITICAL: {name} requires IMMEDIATE maintenance. "
                    f"Health at {health:.0f}% - failure imminent.")
            elif health < 60:
                recs.append(
                    f"WARNING: {name} should be maintained within "
                    f"1-2 weeks. Health at {health:.0f}%.")
            elif health < 80:
                recs.append(
                    f"PLAN: Schedule {name} for routine maintenance. "
                    f"Health at {health:.0f}%.")
        if not recs:
            recs.append("All equipment operating within normal parameters.")
        return "\n".join(recs)

    def save_as_html(self, report: Report) -> str:
        """Save report as HTML file."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename  = f"{report.type}_{timestamp}.html"
        filepath  = self._path / filename

        html = self._render_html(report)
        filepath.write_text(html, encoding="utf-8")
        self._notify(f"[REPORT] Saved: {filepath}")
        return str(filepath)

    def save_as_pdf(self, report: Report) -> str:
        """Save report as PDF (requires reportlab)."""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.platypus import (SimpleDocTemplate,
                Paragraph, Spacer, Table, TableStyle)
            from reportlab.lib import colors
            from reportlab.lib.units import cm

            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filepath  = self._path / f"{report.type}_{timestamp}.pdf"
            doc       = SimpleDocTemplate(str(filepath),
                                         pagesize=A4)
            styles    = getSampleStyleSheet()
            story     = []

            # Title
            story.append(Paragraph(
                report.title, styles["Title"]))
            story.append(Paragraph(
                f"Generated: {report.created.strftime('%Y-%m-%d %H:%M')} | "
                f"Author: {report.author}",
                styles["Normal"]))
            story.append(Spacer(1, 0.5*cm))

            for section in report.sections:
                story.append(Paragraph(
                    section.title, styles["Heading1"]))
                if section.type == "table" and section.data:
                    headers = section.data["headers"]
                    rows    = section.data["rows"]
                    data    = [headers] + rows
                    t = Table(data)
                    t.setStyle(TableStyle([
                        ("BACKGROUND",(0,0),(-1,0),colors.darkblue),
                        ("TEXTCOLOR",  (0,0),(-1,0),colors.white),
                        ("FONTNAME",   (0,0),(-1,0),"Helvetica-Bold"),
                        ("ROWBACKGROUNDS",(0,1),(-1,-1),
                         [colors.lightgrey, colors.white]),
                        ("GRID",       (0,0),(-1,-1),0.5,colors.grey),
                        ("FONTSIZE",   (0,0),(-1,-1),8),
                    ]))
                    story.append(t)
                else:
                    for line in section.content.split("\n"):
                        if line.strip():
                            story.append(Paragraph(
                                line, styles["Normal"]))
                story.append(Spacer(1, 0.3*cm))

            doc.build(story)
            self._notify(f"[REPORT] PDF saved: {filepath}")
            return str(filepath)

        except ImportError:
            # Fallback to HTML
            return self.save_as_html(report)
        except Exception as e:
            self._notify(f"[REPORT] PDF error: {e}")
            return self.save_as_html(report)

    def _render_html(self, report: Report) -> str:
        """Render report as HTML."""
        sections_html = ""
        for sec in report.sections:
            sections_html += f"<h2>{sec.title}</h2>\n"
            if sec.type == "table" and sec.data:
                sections_html += "<table border='1'>\n<tr>"
                for h in sec.data["headers"]:
                    sections_html += f"<th>{h}</th>"
                sections_html += "</tr>\n"
                for row in sec.data["rows"]:
                    sections_html += "<tr>"
                    for cell in row:
                        sections_html += f"<td>{cell}</td>"
                    sections_html += "</tr>\n"
                sections_html += "</table>\n"
            elif sec.type == "code":
                sections_html += (f"<pre style='background:#1a1a2e;"
                                 f"color:#00ff88;padding:12px;"
                                 f"border-radius:4px'>"
                                 f"{sec.content}</pre>\n")
            else:
                content = sec.content.replace("\n","<br>")
                sections_html += f"<p>{content}</p>\n"

        return f"""<!DOCTYPE html>
<html><head>
<meta charset='UTF-8'>
<title>{report.title}</title>
<style>
body{{font-family:Consolas,monospace;background:#0a0f1a;
     color:#d0e8ff;margin:40px}}
h1{{color:#00e5ff;border-bottom:2px solid #1a3a5c;padding-bottom:8px}}
h2{{color:#00ff88;margin-top:24px}}
table{{border-collapse:collapse;width:100%;margin:12px 0}}
th{{background:#0d1526;color:#00e5ff;padding:8px;text-align:left}}
td{{padding:6px 8px;border:1px solid #1a3a5c}}
tr:nth-child(even){{background:#0d1526}}
p{{line-height:1.6;margin:8px 0}}
.meta{{color:#3a5a7a;font-size:12px;margin-bottom:20px}}
</style></head><body>
<h1>{report.title}</h1>
<div class='meta'>
  Generated: {report.created.strftime('%Y-%m-%d %H:%M')} |
  Author: {report.author} |
  Type: {report.type}
</div>
{sections_html}
</body></html>"""

    def quick_report(self, title: str,
                     content: str,
                     llm_callback=None) -> str:
        """Generate a quick report from description."""
        if llm_callback:
            enhanced = llm_callback(
                "docs",
                f"Write a professional technical report about: {content}\n"
                f"Include: Executive Summary, Findings, Recommendations.")
            content = enhanced or content

        report = Report(title, "custom")
        report.add_text("Report Content", content)
        return self.save_as_html(report)
