MODELS = {
    "master": {
        "name": "Llama-3.1-8B — Master Brain",
        "file": "llama3-master.gguf",
        "url":  "https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
        "size_gb": 4.9, "ram_mb": 450, "speed_s": 6, "accuracy": 95,
        "role": "Deep reasoning, planning, complex decisions",
        "triggers": ["analyze","explain","plan","design","think","why","how"],
    },
    "reflex": {
        "name": "Phi-3-Mini — Reflex Brain",
        "file": "phi3-reflex.gguf",
        "url":  "https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf",
        "size_gb": 2.4, "ram_mb": 200, "speed_s": 0.8, "accuracy": 82,
        "role": "Ultra fast responses, simple commands",
        "triggers": ["quick","fast","what is","define","list","show"],
    },
    "plc": {
        "name": "Mistral-7B — PLC Brain",
        "file": "mistral7b-plc.gguf",
        "url":  "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf",
        "size_gb": 4.4, "ram_mb": 400, "speed_s": 5, "accuracy": 93,
        "role": "PLC programming, ladder logic, SCADA, industrial",
        "triggers": ["plc","ladder","rung","coil","contact","scada",
                     "allen bradley","siemens","modbus","profibus",
                     "automation","industrial","hmi","timer","counter"],
    },
    "coder": {
        "name": "DeepSeek-Coder — Code Brain",
        "file": "deepseek-coder.gguf",
        "url":  "https://huggingface.co/TheBloke/deepseek-coder-1.3b-instruct-GGUF/resolve/main/deepseek-coder-1.3b-instruct.Q8_0.gguf",
        "size_gb": 1.4, "ram_mb": 200, "speed_s": 2, "accuracy": 91,
        "role": "Python, scripts, automation code, debugging",
        "triggers": ["code","python","script","function","debug",
                     "error","fix","write code","program","implement"],
    },
    "screen": {
        "name": "Gemma-2B — Screen Brain",
        "file": "gemma2b-screen.gguf",
        "url":  "https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q8_0.gguf",
        "size_gb": 2.5, "ram_mb": 250, "speed_s": 1.5, "accuracy": 88,
        "role": "Screen reading, GUI automation, UI detection",
        "triggers": ["click","screen","button","window","open","close",
                     "gui","interface","navigate","find on screen"],
    },
    "safety": {
        "name": "Gemma-2B-Safety — Safety Brain",
        "file": "gemma2b-safety.gguf",
        "url":  "https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q6_K.gguf",
        "size_gb": 1.9, "ram_mb": 220, "speed_s": 1.5, "accuracy": 94,
        "role": "Safety checks, E-stop, risk assessment, alarms",
        "triggers": ["safety","estop","emergency","risk","alarm",
                     "fault","danger","hazard","sil","interlock","loto"],
    },
    "memory": {
        "name": "MiniLM — Memory Brain",
        "file": "minilm-memory.gguf",
        "url":  "https://huggingface.co/second-state/All-MiniLM-L6-v2-Embedding-GGUF/resolve/main/all-MiniLM-L6-v2-Q8_0.gguf",
        "size_gb": 0.04, "ram_mb": 64, "speed_s": 0.1, "accuracy": 90,
        "role": "Semantic memory, recall, similarity search",
        "triggers": ["remember","recall","search","find","history"],
    },
    "docs": {
        "name": "Qwen2-7B — Documentation Brain",
        "file": "qwen2-docs.gguf",
        "url":  "https://huggingface.co/Qwen/Qwen2-7B-Instruct-GGUF/resolve/main/qwen2-7b-instruct-q4_k_m.gguf",
        "size_gb": 4.5, "ram_mb": 420, "speed_s": 6, "accuracy": 92,
        "role": "Documentation, reports, manuals, technical writing",
        "triggers": ["document","report","manual","write","summarize",
                     "explain in detail","describe","generate report"],
    },
    "learner": {
        "name": "Llama-3.2-3B — Learning Brain",
        "file": "llama3-learner.gguf",
        "url":  "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q8_0.gguf",
        "size_gb": 3.4, "ram_mb": 350, "speed_s": 3, "accuracy": 89,
        "role": "Software learning, OS operations, app automation",
        "triggers": ["learn","teach","how to use","software","application",
                     "operate","tutorial","steps","guide","windows"],
    },
    "ocr": {
        "name": "TrOCR — Vision OCR Brain",
        "file": "trocr-vision.onnx",
        "url":  "https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf",
        "size_gb": 0.1, "ram_mb": 64, "speed_s": 0.2, "accuracy": 96,
        "role": "Read text from screen, OCR, image text extraction",
        "triggers": ["read screen","what does screen say","ocr",
                     "text on screen","read this","extract text"],
    },
    "math": {
        "name": "Phi-3-Math — Math Brain",
        "file": "phi3-math.gguf",
        "url":  "https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf",
        "size_gb": 2.4, "ram_mb": 200, "speed_s": 1, "accuracy": 93,
        "role": "Math, engineering calculations, formulas",
        "triggers": ["calculate","formula","math","convert","equation",
                     "compute","how many","measurement","units"],
    },
}

TOTAL_GB  = sum(m["size_gb"] for m in MODELS.values())
TOTAL_RAM = max(m["ram_mb"]  for m in MODELS.values())
