MODELS = {
    "master":  {"name":"Llama-3.1-8B — Master Brain","file":"llama3-master.gguf","url":"https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf","size_gb":4.9,"ram_mb":450,"speed_s":6,"accuracy":95,"role":"Deep reasoning planning complex decisions","color":"#00e5ff","triggers":["analyze","explain","plan","design","think","why","how","complex"]},
    "reflex":  {"name":"Phi-3-Mini — Reflex Brain","file":"phi3-reflex.gguf","url":"https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf","size_gb":2.4,"ram_mb":200,"speed_s":0.8,"accuracy":82,"role":"Ultra fast responses simple commands","color":"#00ff88","triggers":["quick","fast","what is","define","list","show","tell me"]},
    "plc":     {"name":"Mistral-7B — PLC Brain","file":"mistral7b-plc.gguf","url":"https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf","size_gb":4.4,"ram_mb":400,"speed_s":5,"accuracy":93,"role":"PLC ladder logic SCADA industrial automation","color":"#ff6b2b","triggers":["plc","ladder","rung","coil","contact","scada","allen bradley","siemens","modbus","automation","industrial","hmi","timer","counter"]},
    "coder":   {"name":"DeepSeek-Coder — Code Brain","file":"deepseek-coder.gguf","url":"https://huggingface.co/TheBloke/deepseek-coder-1.3b-instruct-GGUF/resolve/main/deepseek-coder-1.3b-instruct.Q8_0.gguf","size_gb":1.4,"ram_mb":200,"speed_s":2,"accuracy":91,"role":"Python scripts automation code debugging","color":"#bf5fff","triggers":["code","python","script","function","debug","error","fix","program","implement"]},
    "screen":  {"name":"Gemma-2B — Screen Brain","file":"gemma2b-screen.gguf","url":"https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q8_0.gguf","size_gb":2.5,"ram_mb":250,"speed_s":1.5,"accuracy":88,"role":"Screen reading GUI automation UI detection","color":"#ffaa00","triggers":["click","screen","button","window","open","close","gui","navigate","find on screen"]},
    "safety":  {"name":"Gemma-2B-Safety — Safety Brain","file":"gemma2b-safety.gguf","url":"https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q6_K.gguf","size_gb":1.9,"ram_mb":220,"speed_s":1.5,"accuracy":94,"role":"Safety checks estop risk assessment alarms","color":"#ff4444","triggers":["safety","estop","emergency","risk","alarm","fault","danger","sil","interlock","loto"]},
    "memory":  {"name":"MiniLM — Memory Brain","file":"minilm-memory.gguf","url":"https://huggingface.co/second-state/All-MiniLM-L6-v2-Embedding-GGUF/resolve/main/all-MiniLM-L6-v2-Q8_0.gguf","size_gb":0.04,"ram_mb":64,"speed_s":0.1,"accuracy":90,"role":"Semantic memory recall similarity search","color":"#00ffcc","triggers":["remember","recall","search","find","history","previous"]},
    "docs":    {"name":"Qwen2-7B — Documentation Brain","file":"qwen2-docs.gguf","url":"https://huggingface.co/Qwen/Qwen2-7B-Instruct-GGUF/resolve/main/qwen2-7b-instruct-q4_k_m.gguf","size_gb":4.5,"ram_mb":420,"speed_s":6,"accuracy":92,"role":"Documentation reports manuals technical writing","color":"#aaaaff","triggers":["document","report","manual","write","summarize","explain in detail","describe"]},
    "learner": {"name":"Llama-3.2-3B — Learning Brain","file":"llama3-learner.gguf","url":"https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q8_0.gguf","size_gb":3.4,"ram_mb":350,"speed_s":3,"accuracy":89,"role":"Software learning OS operations app automation","color":"#ffdd00","triggers":["learn","teach","how to use","software","application","operate","tutorial","steps","guide"]},
    "ocr":     {"name":"Phi-3-Mini — OCR Vision Brain","file":"phi3-ocr.gguf","url":"https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf","size_gb":2.4,"ram_mb":200,"speed_s":0.5,"accuracy":90,"role":"Read text from screen OCR image text extraction","color":"#ff88ff","triggers":["read screen","ocr","text on screen","read this","extract text","what does screen say","watch screen"]},
    "math":    {"name":"Phi-3-Math — Math Brain","file":"phi3-math.gguf","url":"https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-q4.gguf","size_gb":2.4,"ram_mb":200,"speed_s":1,"accuracy":93,"role":"Math engineering calculations formulas conversions","color":"#88ffaa","triggers":["calculate","formula","math","convert","equation","compute","how many","measurement"]},
}
TOTAL_GB = sum(m["size_gb"] for m in MODELS.values())
